export enum IconEnum {
  ADD = "add",
  ARROW = "arrow",
  CALL = "call",
  CPU = "cpu-charge",
  GLOBAL = "global-edit",
  INSTAGRAM = "instagram",
  MAP = "map",
  CIRCLE = "maximize-circle",
  MENU = "menu",
  MINUS = "minus",
  RANK = "ranking",
  SMS = "sms",
  FACEBOOK = "facebook",
  LOGO = "logo",
  CROSS = "cross",
}
